version: '3.7'

services:
  web:
    build: .
    container_name: true-elogistic-web
    entrypoint:
      [
        './wait-for-it.sh',
        'db:5432',
        '--timeout=5',
        '--strict',
        '--',
        './entrypoint.sh',
      ]
    environment:
      DB_USER: admin
      DB_PASSWORD: secret
      DB_HOST: true-elogistic-db
      DB_NAME: elogistic
      SERVER_PORT: 8080
    ports:
      - '3000:3000'
    volumes:
      - './src:/usr/src/app/src'
    networks:
      - elogistic

  db:
    image: postgres:12.2-alpine
    container_name: true-elogistic-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./src/server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elogistic

networks:
  elogistic:
    external: true
    name: elogistic