version: "3.7"

services:
  web:
    build: .
    container_name: true-elogistic-web
    entrypoint: ["./wait-for-it.sh", "db:5432", "--timeout=5","--strict", "--", "./entrypoint.sh"]
    ports:
      - "3000:3000"
    volumes:
      - "./src:/usr/src/app/src"
    networks:
      - logistic

  db:
    image: postgres:12.2-alpine
    container_name: true-elogistic-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./src/server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - logistic

networks:
  logistic:
    external: true
    name: logistic